PROJ = top_icebreaker

PIN_DEF = icebreaker-examples/icebreaker/icebreaker.pcf
DEVICE = up5k
PACKAGE = sg48

ADD_SRC = led_panel_single.v uart_rx.v

prog: iceprog

include icebreaker-examples/main.mk
